### รู้จักกับ Exception
### การจัดการข้อผิดพลาด

#############################################################################################
score = "555"
number1 = int(input("ป้อนตัวเลข 1 : "))
number2 = int(input("ป้อนตัวเลข 2 : "))
result = number1 / number2
print(score)

#############################################################################################